In [1]:
import torch
import numpy as np

In [2]:
def activation_func(x):
    """sigmoid function"""
    return 1 / (1 + torch.exp(-x))

In [3]:
torch.manual_seed(7)

In [4]:
features = torch.randn((1, 5))
features

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])

In [5]:
weights = torch.randn_like(features)
weights

tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])

In [6]:
bias = torch.randn((1, 1))
bias

tensor([[0.3177]])

In [7]:
torch.mean(features)

tensor(0.4325)

In [8]:
# output of network
res = activation_func(torch.sum(features * weights) + bias)
res

tensor([[0.1595]])

In [9]:
res = activation_func(torch.mm(features, weights.view(5, 1)) + bias)
res

tensor([[0.1595]])

In [10]:
# computing output in presence of hidden layer

features = torch.randn((1, 3))

n_input = features.shape[1] #input unit
n_hidden = 2 #hidden units
n_output = 1 #output units

# weights for inputs to hidden layer
w1 = torch.randn(n_input, n_hidden)
# weights for hidden layer to output layer 
w2 = torch.randn(n_hidden, n_output)

# bias terms
b1 = torch.randn(1, n_hidden)
b2 = torch.randn(1, n_output)

In [11]:
h = activation_func(torch.mm(features, w1) + b1)
print("Result at hidden layer : ", h)

Result at hidden layer :  tensor([[0.6574, 0.4924]])


In [12]:
res = activation_func(torch.mm(h, w2) + b2)
print("Result at output layer : ", res)

Result at output layer :  tensor([[0.8805]])


In [13]:
# numpy to torch

a = np.random.randn(4, 3)
a

array([[ 0.79017111,  0.50292648,  1.59108785],
       [-0.04711493,  0.38264838,  1.30408859],
       [ 0.43074395,  0.72895282,  0.04748182],
       [ 0.41340075,  0.75376453,  0.83033652]])

In [14]:
b = torch.from_numpy(a)
b

tensor([[ 0.7902,  0.5029,  1.5911],
        [-0.0471,  0.3826,  1.3041],
        [ 0.4307,  0.7290,  0.0475],
        [ 0.4134,  0.7538,  0.8303]], dtype=torch.float64)

In [15]:
b.numpy()

array([[ 0.79017111,  0.50292648,  1.59108785],
       [-0.04711493,  0.38264838,  1.30408859],
       [ 0.43074395,  0.72895282,  0.04748182],
       [ 0.41340075,  0.75376453,  0.83033652]])

In [16]:
# inplace operations

b.mul_(2)

tensor([[ 1.5803,  1.0059,  3.1822],
        [-0.0942,  0.7653,  2.6082],
        [ 0.8615,  1.4579,  0.0950],
        [ 0.8268,  1.5075,  1.6607]], dtype=torch.float64)

In [17]:
# both types get affected

a

array([[ 1.58034222,  1.00585296,  3.18217569],
       [-0.09422986,  0.76529676,  2.60817718],
       [ 0.86148789,  1.45790564,  0.09496364],
       [ 0.8268015 ,  1.50752906,  1.66067303]])